--- 
version: "3"
services:   
  prometheus: 
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    image: "prom/prometheus:latest"
    ports: 
      - "9090:9090"
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus_data:/prometheus"
  node-exporter: 
    image: "prom/node-exporter:latest"
    ports: 
      - "9100:9100"
  buildkite-exporter: 
    image: "buildkite_exporter:latest"
    ports: 
      - "9260:9260"
    environment:
      - BK_ORGANIZATION
      - BK_ACCESS_TOKEN
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_data:/var/lib/grafana"