--- 
global: 
  external_labels: 
    monitor: my-monitor
  scrape_interval: 5s
scrape_configs: 
  - job_name: prometheus
    static_configs: 
      - targets: 
          - "localhost:9090"
  - job_name: node-exporter
    static_configs: 
      - targets: 
          - "node-exporter:9100"
  - job_name: buildkite-exporter
    static_configs: 
      - targets: 
          - "buildkite-exporter:9260"